<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // ─── Commercial Opportunities ─────────────────────────────────────────
        Schema::create('commercial_opportunities', function (Blueprint $table) {
            $table->id();
            $table->foreignId('trend_id')->constrained()->cascadeOnDelete();
            $table->foreignId('country_id')->nullable()->constrained()->nullOnDelete();

            // Scores (0-100)
            $table->integer('opportunity_score')->default(0);
            $table->integer('demand_score')->default(0);
            $table->integer('competition_score')->default(0);
            $table->integer('momentum_score')->default(0);
            $table->integer('timing_score')->default(0);
            $table->integer('confidence')->default(0);

            // Product concept generated by Creative Director module
            $table->text('suggested_product_name')->nullable();
            $table->string('suggested_silhouette', 100)->nullable();
            $table->json('suggested_colors')->default('[]');
            $table->json('suggested_graphics')->default('[]');
            $table->decimal('suggested_price_min', 10, 2)->nullable();
            $table->decimal('suggested_price_max', 10, 2)->nullable();
            $table->text('suggested_target_audience')->nullable();
            $table->text('reasoning')->nullable();
            $table->json('risks')->default('[]');
            $table->json('evidence')->default('[]');

            $table->timestamps();

            $table->index(['trend_id', 'opportunity_score']);
            $table->index('country_id');
        });

        // ─── Competitors ──────────────────────────────────────────────────────
        Schema::create('competitors', function (Blueprint $table) {
            $table->id();
            $table->foreignId('trend_id')->constrained()->cascadeOnDelete();
            $table->foreignId('brand_id')->nullable()->constrained()->nullOnDelete();
            $table->integer('product_count')->default(0);
            $table->decimal('price_min', 10, 2)->nullable();
            $table->decimal('price_max', 10, 2)->nullable();
            $table->integer('strength')->default(0); // 0-100
            $table->text('notes')->nullable();
            $table->timestamp('created_at')->useCurrent();

            $table->index('trend_id');
        });

        // ─── Content Features ─────────────────────────────────────────────────
        Schema::create('content_features', function (Blueprint $table) {
            $table->id();
            $table->foreignId('raw_image_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('raw_document_id')->nullable()->constrained()->nullOnDelete();

            // Composition analysis
            $table->string('composition', 50)->nullable();
            $table->string('camera_angle', 50)->nullable();
            $table->string('framing', 50)->nullable();
            $table->string('lighting', 50)->nullable();
            $table->boolean('uses_flash')->nullable();
            $table->string('background_type', 50)->nullable();
            $table->string('environment', 50)->nullable();

            // Subject analysis
            $table->integer('person_count')->nullable();
            $table->boolean('has_full_body')->nullable();
            $table->boolean('has_close_up')->nullable();

            // Visibility scores (0-100)
            $table->integer('product_visibility')->nullable();
            $table->integer('garment_visibility')->nullable();
            $table->integer('graphic_visibility')->nullable();

            // Style
            $table->integer('styling_complexity')->nullable();
            $table->string('image_style', 50)->nullable();

            // Detected elements
            $table->json('dominant_colors')->default('[]');
            $table->json('detected_garments')->default('[]');
            $table->json('detected_brands')->default('[]');

            $table->timestamp('created_at')->useCurrent();

            $table->index('raw_image_id');
            $table->index('raw_document_id');
        });

        // For pgvector: add embedding column separately
        // This is done in a separate statement because Blueprint doesn't support vector type
        // The migration registers it and the actual column is added via raw SQL below

        // ─── Advertising Patterns ─────────────────────────────────────────────
        Schema::create('advertising_patterns', function (Blueprint $table) {
            $table->id();
            $table->string('formula_name', 255)->nullable();
            $table->json('formula_structure')->nullable(); // ordered steps
            $table->string('hook_type', 100)->nullable();
            $table->string('product_reveal_timing', 50)->nullable();
            $table->string('cta_type', 100)->nullable();
            $table->integer('frequency')->default(0);
            $table->decimal('avg_engagement', 12, 2)->nullable();
            $table->decimal('conversion_proxy', 5, 2)->nullable();
            $table->integer('confidence')->default(0);
            $table->json('examples')->default('[]');
            $table->timestamp('created_at')->useCurrent();
        });

        // ─── Trend Predictions ────────────────────────────────────────────────
        Schema::create('trend_predictions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('trend_id')->constrained()->cascadeOnDelete();
            $table->foreignId('country_id')->nullable()->constrained()->nullOnDelete();
            $table->string('model_name', 100)->nullable();
            $table->string('model_version', 50)->nullable();
            $table->string('prompt_version', 50)->nullable();
            $table->integer('prediction_horizon')->nullable(); // days ahead
            $table->date('prediction_date')->nullable();
            $table->date('target_date')->nullable();

            // Probability forecasts (0-100)
            $table->integer('growth_probability')->nullable();
            $table->integer('decline_probability')->nullable();
            $table->integer('saturation_probability')->nullable();
            $table->integer('death_probability')->nullable();
            $table->json('momentum_forecast')->nullable(); // time series

            $table->integer('confidence')->default(0);
            $table->text('reasoning')->nullable();
            $table->json('input_snapshot')->default('{}');

            $table->timestamp('created_at')->useCurrent();

            $table->index('trend_id');
            $table->index('prediction_date');
        });

        // ─── Prediction Outcomes (for backtesting) ────────────────────────────
        Schema::create('prediction_outcomes', function (Blueprint $table) {
            $table->id();
            $table->foreignId('prediction_id')->constrained('trend_predictions')->cascadeOnDelete();
            $table->decimal('actual_growth', 8, 4)->nullable();
            $table->string('actual_lifecycle_stage', 30)->nullable();
            $table->decimal('accuracy_score', 5, 2)->nullable();
            $table->decimal('forecast_error', 8, 4)->nullable();
            $table->timestamp('evaluated_at')->useCurrent();
        });

        // ─── Model Runs (ML tracking) ─────────────────────────────────────────
        Schema::create('model_runs', function (Blueprint $table) {
            $table->id();
            $table->string('model_name', 100)->nullable();
            $table->string('model_version', 50)->nullable();
            $table->foreignId('prompt_id')->nullable()->constrained('prompt_versions')->nullOnDelete();
            $table->string('task', 100)->nullable();
            $table->char('input_hash', 64)->nullable();
            $table->json('output')->nullable();
            $table->integer('tokens_used')->nullable();
            $table->integer('duration_ms')->nullable();
            $table->boolean('success')->default(true);
            $table->text('error')->nullable();
            $table->timestamp('created_at')->useCurrent();

            $table->index('task');
            $table->index('model_name');
            $table->index('created_at');
        });

        // ─── Add vector embedding column for content_features ─────────────────
        // Only on PostgreSQL with pgvector
        if (DB::getDriverName() === 'pgsql') {
            try {
                DB::statement('ALTER TABLE content_features ADD COLUMN image_embedding vector(512)');
                DB::statement('CREATE INDEX idx_content_features_embedding ON content_features USING ivfflat (image_embedding vector_cosine_ops) WITH (lists = 100)');
            } catch (\Exception $e) {
                // pgvector not available — embedding will be stored as JSON fallback
                \Illuminate\Support\Facades\Log::warning('pgvector not available, skipping embedding index: ' . $e->getMessage());
            }
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('model_runs');
        Schema::dropIfExists('prediction_outcomes');
        Schema::dropIfExists('trend_predictions');
        Schema::dropIfExists('advertising_patterns');
        Schema::dropIfExists('content_features');
        Schema::dropIfExists('competitors');
        Schema::dropIfExists('commercial_opportunities');
    }
};
